apiVersion: apps/v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"

---
apiVersion: apps/v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
storageClassName: manual
accessModes:
  - ReadWriteOnce
resources:
  requests:
    storage: 3Gi
