---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapi-deployment
  labels:
    app: goapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapi
  template:
    metadata:
      name: goapi-deployment
      labels:
        app: goapi
    spec:
      containers:
        - name: goapi
          image: docker.io/s4ych33se/zephyr-goapi
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "300m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db_password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db_user
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db_host
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db_name
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: token_secret
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: session_secret
            - name: EMAIL_AUTH
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: email_auth
            - name: CPU_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: cpu_limit
            - name: CPU_REQUEST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: cpu_request
            - name: MEMORY_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: memory_limit
            - name: MEMORY_REQUEST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: memory_request
            - name: DISK_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: disk_limit
            - name: DISK_REQUEST
              valueFrom:  
                configMapKeyRef:
                  name: app-config
                  key: disk_request
---
apiVersion: v1
kind: Service
metadata:
  name: goapi-svc
  labels:
    app: goapi-svc
spec:
  ports:
    - port: 80
  selector:
    app: goapi

