---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  session_secret: ODE1NWIyODgwOWQ2MGJlMDQxNjM4N2E5OWM5NDI5NzU=
  token_secret: MTQyNGU2ZjBhMTQ2MzM5Yjc0YWYyNzlkNjRhOTIzNjI=
  email_id: cGFsc2FnbmlrMjEwMkBnbWFpbC5jb20=
  email_auth: bm90YXNlY3JldA==
  instance_name_secret: N2Q2YzllOGY2ODcwZWZhNGU1YmJiYzU3YjdiY2JmZDM=
  db_host: ZGF0YWJhc2Utc3Zj
  db_user: cG9zdGdyZXM=
  db_password: eW91ci9tb21tYS9zb2ZhdC90aGVyZWlzL2ExMmhvdXIvdGltZS9kaWZmZXJlbmNlL2Fsb25nL2hlci93YWlzdA==
  db_name: cG9zdGdyZXM=